# Generated by Django 3.2.7 on 2021-09-04 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('addition', models.TextField(blank=True, max_length=300, null=True)),
                ('access', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('url', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField()),
                ('image_path', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'camp_site',
            },
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'site_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mail_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('camp_site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='camp_sites.campsite')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('pref_name', models.CharField(blank=True, max_length=30, null=True)),
                ('city_name', models.CharField(blank=True, max_length=30, null=True)),
                ('other_address', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('camp_site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='camp_sites.campsite')),
                ('let', models.FloatField()),
                ('lon', models.FloatField()),
            ],
            options={
                'db_table': 'coordinate',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('Comment', models.TextField()),
                ('camp_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp_sites.campsite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp_sites.user')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Ikitai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp_sites.campsite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp_sites.user')),
            ],
            options={
                'db_table': 'ikitai',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_exist', models.BooleanField(default=False)),
                ('camp_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp_sites.campsite')),
            ],
            options={
                'db_table': 'facility',
            },
        ),
        migrations.AddField(
            model_name='campsite',
            name='site_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp_sites.sitetype'),
        ),
        migrations.AddConstraint(
            model_name='ikitai',
            constraint=models.UniqueConstraint(fields=('user', 'camp_site'), name='unique_ikitai'),
        ),
    ]
